SeriesListWeb/Models/ErrorViewModel.cs
namespace SeriesListWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SeriesListWeb/Models/Series.cs
using System.ComponentModel.DataAnnotations;

namespace SeriesListWeb.Models
{
    public class Series
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Genre { get; set; }
        public bool Watch { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}

SeriesListWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SeriesListWeb.Models;
using System.Diagnostics;

namespace SeriesListWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SeriesListWeb/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using SeriesListWeb.Data;
using SeriesListWeb.Models;

namespace SeriesListWeb.Controllers
{
    public class SeriesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SeriesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Series> objSeriesList = _db.Serie;
            return View(objSeriesList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Series obj)
        {
            if(obj.Name == obj.Genre)
            {
                ModelState.AddModelError("name", "The Genre cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _db.Serie.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Serie created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var serieFromDb = _db.Serie.Find(id);
            if(serieFromDb == null)
            {
                return NotFound();
            }
            return View(serieFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Series obj)
        {
            if (obj.Name == obj.Genre)
            {
                ModelState.AddModelError("name", "The Genre cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _db.Serie.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Serie updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var serieFromDb = _db.Serie.Find(id);
            if (serieFromDb == null)
            {
                return NotFound();
            }
            return View(serieFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Serie.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            _db.Serie.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Serie deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

SeriesListWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SeriesListWeb/Views/Series/Create.cshtml
@model Series

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Serie</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Genre"></label>
            <input asp-for="Genre" class="form-control" />
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Watch"></label>
            <div>
                <input asp-for="Watch" class="form-check-input" type="checkbox" id="flexCheckDefault" style="width:25px; height:25px">
            </div>
            <span asp-validation-for="Watch" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Series" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

@section Scripts
{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

SeriesListWeb/Views/Series/Delete.cshtml
@model Series

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Serie</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Genre"></label>
            <input asp-for="Genre" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Watch"></label>
            <div>
                <input asp-for="Watch" disabled class="form-check-input" type="checkbox" id="flexCheckDefault" style="width:25px; height:25px">
            </div>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Series" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

SeriesListWeb/Views/Series/Edit.cshtml
@model Series

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Serie</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Genre"></label>
            <input asp-for="Genre" class="form-control" />
            <span asp-validation-for="Genre" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Watch"></label>
            <div>
                <input asp-for="Watch" class="form-check-input" type="checkbox" id="flexCheckDefault" style="width:25px; height:25px">
            </div>
            <span asp-validation-for="Watch" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Series" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

SeriesListWeb/Views/Series/Index.cshtml
@model IEnumerable<Series>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Series List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Series" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Serie
            </a>
        </div>
    </div>
</div>
<br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Genre
            </th>
            <th>
                Watch?
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="35%">
                    @obj.Name
                </td>
                <td width="25%">
                    @obj.Genre
                </td>
                <td width="15%">
                    @if(obj.Watch == true)
                    {
                        <p>Yes</p>
                    }
                    @if(obj.Watch == false)
                    {
                        <p>No</p>
                    }
            </td>
                <td>
                    <div class="w-50 btn-group" role="group">
                        <a asp-controller="Series" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                    </div>
                    <div class="w-50 btn-group" role="group" style="float: left">
                        <a asp-controller="Series" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash"></i> Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

SeriesListWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeriesListWeb</title>
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SeriesListWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Series" asp-action="Index">Series</a>
                    </li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SeriesListWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SeriesListWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}